---
name: Tweet on Release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  twitter:
    name: ðŸ¦ Tweet the release
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: >
            A new version of ${{ github.event.repository.name }} just released ðŸŽ‰
            @klaasnicolaas #release #bot #assistant

            Check out the release notes here: ${{ github.event.release.html_url }}
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
